### ISSUE TITLE
Where do the event markers/lines come from?

### ISSUE THREAD

**Issue by jzyrobert** [mojoaxel/flot-events#7]
Hi,
I wonder where the graphics for the markers/lines is coming from, as I can see they are a div with "events_marker" and "events_line" class, but I cannot find any reference to any CSS or code that would place the image into the div.

Thanks

**Comment by mojoaxel** [comment]
### events_line

https://github.com/mojoaxel/flot-events/blob/master/jquery.flot.events.js#L256-L266

## events_marker

https://github.com/mojoaxel/flot-events/blob/master/jquery.flot.events.js#L270-L279

**Comment by jzyrobert** [comment]
Hi,

Sorry, I understand where in the code they are created, but I am rather unfamiliar with front-end coding.

I don't see anything that actually creates the triangle/line graphic, is that something just built into flot/something else?

**Comment by mojoaxel** [comment]
> I don't see anything that actually creates the triangle/line graphic, is that something just built into flot/something else?

The triangle is done with pure CSS.
Here is an example: https://css-tricks.com/snippets/css/css-triangle/

**Comment by jzyrobert** [comment]
I did not know that was possible, thank you!
